/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSecretaryIndexRouteImport } from './routes/_authenticated/secretary/index'
import { Route as AuthenticatedConsumerIndexRouteImport } from './routes/_authenticated/consumer/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSecretaryUsersRouteImport } from './routes/_authenticated/secretary/users'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSecretariesRouteImport } from './routes/_authenticated/admin/secretaries'
import { Route as AuthenticatedAdminRatesRouteImport } from './routes/_authenticated/admin/rates'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin/locations'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin/invoices'
import { Route as AuthenticatedAdminDevicesRouteImport } from './routes/_authenticated/admin/devices'
import { Route as AuthenticatedAdminConsumersRouteImport } from './routes/_authenticated/admin/consumers'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminMediaCoverageRouteImport } from './routes/_authenticated/admin/media-coverage'
import { Route as AuthenticatedAdminConsumersIdRouteImport } from './routes/_authenticated/admin/consumers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecretaryIndexRoute =
  AuthenticatedSecretaryIndexRouteImport.update({
    id: '/secretary/',
    path: '/secretary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsumerIndexRoute =
  AuthenticatedConsumerIndexRouteImport.update({
    id: '/consumer/',
    path: '/consumer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecretaryUsersRoute =
  AuthenticatedSecretaryUsersRouteImport.update({
    id: '/secretary/users',
    path: '/secretary/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSecretariesRoute =
  AuthenticatedAdminSecretariesRouteImport.update({
    id: '/admin/secretaries',
    path: '/admin/secretaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRatesRoute = AuthenticatedAdminRatesRouteImport.update({
  id: '/admin/rates',
  path: '/admin/rates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/admin/locations',
    path: '/admin/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/admin/invoices',
    path: '/admin/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDevicesRoute =
  AuthenticatedAdminDevicesRouteImport.update({
    id: '/admin/devices',
    path: '/admin/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConsumersRoute =
  AuthenticatedAdminConsumersRouteImport.update({
    id: '/admin/consumers',
    path: '/admin/consumers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediaCoverageRoute =
  AuthenticatedAdminMediaCoverageRouteImport.update({
    id: '/admin/media-coverage',
    path: '/admin/media-coverage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConsumersIdRoute =
  AuthenticatedAdminConsumersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminConsumersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/consumers': typeof AuthenticatedAdminConsumersRouteWithChildren
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/media-coverage': typeof AuthenticatedAdminMediaCoverageRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/secretaries': typeof AuthenticatedAdminSecretariesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/secretary/users': typeof AuthenticatedSecretaryUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/consumer/': typeof AuthenticatedConsumerIndexRoute
  '/secretary/': typeof AuthenticatedSecretaryIndexRoute
  '/admin/consumers/$id': typeof AuthenticatedAdminConsumersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/consumers': typeof AuthenticatedAdminConsumersRouteWithChildren
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/media-coverage': typeof AuthenticatedAdminMediaCoverageRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/secretaries': typeof AuthenticatedAdminSecretariesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/secretary/users': typeof AuthenticatedSecretaryUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/consumer': typeof AuthenticatedConsumerIndexRoute
  '/secretary': typeof AuthenticatedSecretaryIndexRoute
  '/admin/consumers/$id': typeof AuthenticatedAdminConsumersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/consumers': typeof AuthenticatedAdminConsumersRouteWithChildren
  '/_authenticated/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/media-coverage': typeof AuthenticatedAdminMediaCoverageRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/_authenticated/admin/secretaries': typeof AuthenticatedAdminSecretariesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/secretary/users': typeof AuthenticatedSecretaryUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/consumer/': typeof AuthenticatedConsumerIndexRoute
  '/_authenticated/secretary/': typeof AuthenticatedSecretaryIndexRoute
  '/_authenticated/admin/consumers/$id': typeof AuthenticatedAdminConsumersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/consumers'
    | '/admin/devices'
    | '/admin/invoices'
    | '/admin/media-coverage'
    | '/admin/locations'
    | '/admin/rates'
    | '/admin/secretaries'
    | '/admin/users'
    | '/secretary/users'
    | '/admin/'
    | '/consumer/'
    | '/secretary/'
    | '/admin/consumers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/consumers'
    | '/admin/devices'
    | '/admin/invoices'
    | '/admin/media-coverage'
    | '/admin/locations'
    | '/admin/rates'
    | '/admin/secretaries'
    | '/admin/users'
    | '/secretary/users'
    | '/admin'
    | '/consumer'
    | '/secretary'
    | '/admin/consumers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/consumers'
    | '/_authenticated/admin/devices'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/media-coverage'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/rates'
    | '/_authenticated/admin/secretaries'
    | '/_authenticated/admin/users'
    | '/_authenticated/secretary/users'
    | '/_authenticated/admin/'
    | '/_authenticated/consumer/'
    | '/_authenticated/secretary/'
    | '/_authenticated/admin/consumers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/': {
      id: '/_authenticated/secretary/'
      path: '/secretary'
      fullPath: '/secretary/'
      preLoaderRoute: typeof AuthenticatedSecretaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consumer/': {
      id: '/_authenticated/consumer/'
      path: '/consumer'
      fullPath: '/consumer/'
      preLoaderRoute: typeof AuthenticatedConsumerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/secretary/users': {
      id: '/_authenticated/secretary/users'
      path: '/secretary/users'
      fullPath: '/secretary/users'
      preLoaderRoute: typeof AuthenticatedSecretaryUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/secretaries': {
      id: '/_authenticated/admin/secretaries'
      path: '/admin/secretaries'
      fullPath: '/admin/secretaries'
      preLoaderRoute: typeof AuthenticatedAdminSecretariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rates': {
      id: '/_authenticated/admin/rates'
      path: '/admin/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AuthenticatedAdminRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/media-coverage': {
      id: '/_authenticated/admin/media-coverage'
      path: '/admin/media-coverage'
      fullPath: '/admin/media-coverage'
      preLoaderRoute: typeof AuthenticatedAdminMediaCoverageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/devices': {
      id: '/_authenticated/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthenticatedAdminDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/consumers': {
      id: '/_authenticated/admin/consumers'
      path: '/admin/consumers'
      fullPath: '/admin/consumers'
      preLoaderRoute: typeof AuthenticatedAdminConsumersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/consumers/$id': {
      id: '/_authenticated/admin/consumers/$id'
      path: '/$id'
      fullPath: '/admin/consumers/$id'
      preLoaderRoute: typeof AuthenticatedAdminConsumersIdRouteImport
      parentRoute: typeof AuthenticatedAdminConsumersRoute
    }
  }
}

interface AuthenticatedAdminConsumersRouteChildren {
  AuthenticatedAdminConsumersIdRoute: typeof AuthenticatedAdminConsumersIdRoute
}

const AuthenticatedAdminConsumersRouteChildren: AuthenticatedAdminConsumersRouteChildren =
  {
    AuthenticatedAdminConsumersIdRoute: AuthenticatedAdminConsumersIdRoute,
  }

const AuthenticatedAdminConsumersRouteWithChildren =
  AuthenticatedAdminConsumersRoute._addFileChildren(
    AuthenticatedAdminConsumersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminConsumersRoute: typeof AuthenticatedAdminConsumersRouteWithChildren
  AuthenticatedAdminDevicesRoute: typeof AuthenticatedAdminDevicesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminMediaCoverageRoute: typeof AuthenticatedAdminMediaCoverageRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminRatesRoute: typeof AuthenticatedAdminRatesRoute
  AuthenticatedAdminSecretariesRoute: typeof AuthenticatedAdminSecretariesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedSecretaryUsersRoute: typeof AuthenticatedSecretaryUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedConsumerIndexRoute: typeof AuthenticatedConsumerIndexRoute
  AuthenticatedSecretaryIndexRoute: typeof AuthenticatedSecretaryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminConsumersRoute:
    AuthenticatedAdminConsumersRouteWithChildren,
  AuthenticatedAdminDevicesRoute: AuthenticatedAdminDevicesRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminMediaCoverageRoute: AuthenticatedAdminMediaCoverageRoute,
  AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
  AuthenticatedAdminRatesRoute: AuthenticatedAdminRatesRoute,
  AuthenticatedAdminSecretariesRoute: AuthenticatedAdminSecretariesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedSecretaryUsersRoute: AuthenticatedSecretaryUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedConsumerIndexRoute: AuthenticatedConsumerIndexRoute,
  AuthenticatedSecretaryIndexRoute: AuthenticatedSecretaryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
